### ISSUE TITLE
[1.16.3] Server crashes

### ISSUE THREAD

**Issue by JuergenSchT** [LudoCrypt/True-Secret-Rooms#2]
TSR works fine on singleplayer. But when trying to place a solid camo block on my server, it crashed.
On server reload, the camo block showed up fine. When trying to place a camo block, the server crashed again.
On server reload, both blocks showed up fine. I then grabbed a Staff of Camo and right-clicked the face of one of the camo blocks. The server... crashed.
[These are the crashes for placing a camo block](https://pastebin.com/2yM56GJ7) [they are identical].
[This is a crash for clicking a camo block with the staff](https://pastebin.com/RX93AZ0r).
Then I looked at the server log, [and found this error](https://pastebin.com/mJxuHSBh). Hopefully, it might be useful.

**Comment by LudoCrypt** [comment]
Fixed in latest version
