### ISSUE TITLE
Applied Energistics 2 - Solid Camo Block - Smart Covered Cable - Client Crash on Render

### ISSUE THREAD

**Issue by crazed014** [LudoCrypt/True-Secret-Rooms#4]
When applying smart covered cable to a Solid Camo Block with the Camo Wand causes client crashes. 

Even if not supporting 3rd party mods would be advisable to add custom exception for error.

```The game crashed whilst tesselating block in world - indigo renderer
Error: java.lang.IllegalStateException
Exit Code: -1```

Crash log: https://pastebin.com/gQ7DwWZW

**Comment by LudoCrypt** [comment]
That may be due to it being a block entity, or it being a model. Its really only safe to have camo blocks be for full blocks, though sometimes models do work. Im not sure about the issue exactly, so I don't know how to fix it. Just be careful with models and block entities
